name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build_and_test_stable:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions-rs/toolchain@v1
      with:
          toolchain: stable

    - name: Build against current compiler        
      run: cargo build
    - name: Run tests against current compiler
      run: cargo test --no-fail-fast
    - name: Check if rust code is correctly formatted
      run: cargo fmt -- --check
    - name: Check against clippy lints
      run: cargo clippy --all-targets --all-features -- -D warnings

  build_and_test_1_41:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions-rs/toolchain@v1
      with:
          toolchain: 1.41

    - name: Build against rust 1.41
      run: cargo build --verbose
    - name: Run tests against rust 1.41
      run: cargo test --verbose
